[env]
ANDROID_NDK_ROOT = "/Volumes/SSD_APPS/android-sdk/ndk"

[target.aarch64-linux-android]
linker = "/Volumes/SSD_APPS/android-sdk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android34-clang"

[target.armv7-linux-androideabi]
linker = "/Volumes/SSD_APPS/android-sdk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi34-clang"

[target.x86_64-linux-android]
linker = "/Volumes/SSD_APPS/android-sdk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86_64-linux-android34-clang"

[target.i686-linux-android]
linker = "/Volumes/SSD_APPS/android-sdk/ndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/i686-linux-android34-clang"